---
- name: Ensure user deploy
  user:
    name: deploy

- name: increase file descriptor limit
  pam_limits:
    domain: deploy
    limit_item: nofile
    value: 4096
    use_max: yes
    limit_type: soft

- name: install yarn globally
  tags:
    - yarn
  shell: npm install --global yarn

- name: ensure apps directory
  file:
    state: directory
    mode: 0777
    path: /opt/apps

- name: Creates log directory
  file:
    path: /var/log/api-particulier
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0744

- name: Ensure log file exists
  file:
    path: /var/log/api-particulier/api-particulier.log
    state: touch
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0644

- name: create app directory for api-particulier
  file:
    state: directory
    mode: 0775
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    path: /opt/apps/api-particulier

- name: create configuration directory for api-particulier
  file:
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0775
    path: /etc/api-particulier
  tags:
    - configure-api-particulier

- name: create certificate directory for api-particulier
  file:
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0770
    path: /etc/api-particulier/ssl

- name: copy chain certificate
  copy:
    src: "{{ inventory_dir }}/../../certificates/particulier-caf.rgs.crt"
    dest: /etc/api-particulier/ssl/particulier-caf.bundle.crt
  when: "api_particulier_environment != 'development'"
  notify:
    - restart api-particulier

- name: copy encrypted keys
  copy:
    src: "{{ inventory_dir }}/../../certificates/particulier-caf.rgs.key"
    dest: /etc/api-particulier/ssl/particulier-caf.key
  register: encrypted_certif
  when: "api_particulier_environment != 'development'"
  notify:
    - restart api-particulier

- name: write configuration for api-particulier
  template:
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0664
    src: api-particulier.conf.j2
    dest: /etc/api-particulier/api-particulier.conf
  notify:
    - restart api-particulier
  tags:
    - configure-api-particulier

- name: create systemd service for API Particulier
  template:
    owner: root
    group: root
    mode: 0644
    src: api-particulier.service.j2
    dest: /etc/systemd/system/api-particulier.service
  register: api_particulier_unit

- name: reload systemd daemon
  shell: systemctl daemon-reload
  when: api_particulier_unit.changed
  notify:
    - restart api-particulier

- name: setup vhost for particulier.api.gouv.fr
  template:
    src: particulier.api.gouv.conf.j2
    dest: /etc/nginx/sites-available/particulier.api.gouv.fr.conf
    mode: 0644
  notify: restart nginx

- name: enable vhost particulier.api.gouv.fr
  file:
    state: link
    src: /etc/nginx/sites-available/particulier.api.gouv.fr.conf
    dest: /etc/nginx/sites-enabled/particulier.api.gouv.fr.conf
  notify: restart nginx

- meta: flush_handlers
