---
ansible_user: vagrant
api_particulier_environment: development
api_particulier_server_name: particulier-development.api.gouv.fr
ssl_strategy: self-signed
app_user: vagrant
main_network_interface: eth1

api_particulier_nb_workers: 1

api_particulier_caf_stub: true

api_particulier_svair_host: http://localhost:3077
svair_mock_port: 3077
particulier_auth_api_port: 7000

monitoring_server_name: monitoring-development.particulier-infra.api.gouv.fr
api_elk_stats_port: 3004

ip_restriction:
  whitelist:
    - 192.168.56.1

load_balancing_ips:
  app1-development.particulier-infra.api.gouv.fr:
    - 192.168.56.36
    - 192.168.56.37
    - 192.168.56.38
  app2-development.particulier-infra.api.gouv.fr:
    - 192.168.56.46
    - 192.168.56.47
    - 192.168.56.48
