name: Tests

on: [push]

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      # For some reason, Github Action is not able to install a git-based npm dependency inside docker
      # The faulty dependency is svair-api, used in two different version to maintain retro-compatibility
      # Therefore we install the npm dependencies directly in the vm as a workaround
      - run: npm i
        working-directory: api-particulier
      - run: docker-compose run api-particulier-auth npm i
      - run: docker-compose run svair-mock npm i
      - run: docker-compose run integration-test npm i
      - name: Build and test the docker stack
        run: docker-compose up --exit-code-from integration-test
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_API_URL: ${{ secrets.AIRTABLE_API_URL }}
  api-particulier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
        working-directory: ./api-particulier
      - run: npm test
        working-directory: ./api-particulier
        env:
          CI: true
  api-particulier-auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Launch MongoDB
        uses: wbari/start-mongoDB@v0.2
        with:
          mongoDBVersion: "4.2"
      - run: npm ci
        working-directory: ./api-particulier-auth
      - run: npm test
        working-directory: ./api-particulier-auth
        env:
          CI: true
  svair-mock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
        working-directory: ./svair-mock
      - run: npm test
        working-directory: ./svair-mock
        env:
          CI: true
